### PR TITLE
Fix projects

### LINKED ISSUE #291: Projects not loading
### Description

A recnet bug when loading the page is in need of fixing.

image
image

### Screenshots

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by barel-mishal**

### CODE REVIEW

File: app/[locale]/projects/page.tsx [hunk 1]
```diff
@@ -83,32 +84,37 @@ const ProjectsPage = () => {
...
-        projects.filter((p: Project) =>
-          p.item.data.repository.name
-            .toLocaleLowerCase()
-            .trim()
-            .includes(searchByProjectNameValue.toLocaleLowerCase().trim())
-        )
+      const projecteFilterdByName = projects.filter((p: Project) =>
+        p.item?.name?.toLocaleLowerCase()
+          .trim()
+          .includes(searchByProjectNameValue.toLocaleLowerCase().trim())
```
Comment (Tamir198) [inline app/[locale]/projects/page.tsx:90]: If you are not passing any param to `toLocaleLowerCase` will it be any different than the `toLowerCase` name?

File: types/project.ts [hunk 2]
```diff
@@ -13,68 +15,116 @@ export type IProjectsDataResponse = {
...
-  meta: Meta;
-  __v: number;
-};
+const dateToString = z.coerce.date().or(z.string());
 
-export type Item = {
-  data: Data;
-};
+// Define the summary schema using Zod
+const SummarySchema = z.object({
```
Comment (Tamir198) [inline types/project.ts:21]: I don`t think this comment adds anything and can be removed.

File: types/project.ts [hunk 3]
```diff
@@ -13,68 +15,116 @@ export type IProjectsDataResponse = {
...
-  url: string;
-  createdAt: Date;
-  updatedAt: Date;
-  stargazerCount: number;
-  languages: Languages;
-  collaborators: null;
-  contributors: Contributors;
-};
+// Infer the TypeScript type from the summary schema
+export type Project = z.infer<typeof SummarySchema>;
```
Comment (Tamir198) [inline types/project.ts:63]: Same about this comment

File: types/project.ts [hunk 4]
```diff
@@ -13,68 +15,116 @@ export type IProjectsDataResponse = {
...
-  node: ContributorNode;
-};
+// export type Project = {
+//   _id: string;
+//   timestamp: Date;
+//   item: Item;
+//   error: null;
+//   meta: Meta;
+//   __v: number;
+// };
```
Comment (Tamir198) [inline types/project.ts:73]: Also remove all of this commented section

**Review by Tamir198 — CHANGES_REQUESTED** [review]

File: actions/fetchProjectsData.ts [hunk 5]
```diff
@@ -12,6 +12,7 @@ export type ProjectPaginationRequest = {
   filter?: ProjectPaginationFilter;
 };
 
+// const PROJECT_API_ENDPOINT = "http://localhost:8080/projects"
 const PROJECT_API_ENDPOINT = 'https://baas-data-provider.onrender.com/projects';
```
[the remark this answers is not in the document]
Comment (barel-mishal) [reply actions/fetchProjectsData.ts:16]: Hi @Tamir198,

Thank you for pointing that out. The commented line was left there for reference during development, but it’s no longer needed. I will remove it to clean up the code.

File: actions/fetchProjectsData.ts [hunk 6]
```diff
@@ -26,12 +27,29 @@ async function fetchProjectsData({
...
-
+  
   // fetch from endpoint POST with page, limit, filter as IProjectsDataResponse
-  const { projects, total, languages, pageLanguages, timestamp } =
-    await response.json();
+  const data =
+  await response.json() as IProjectsDataResponse;
+
+  const parsedProjects = SummaryProjectType.array().safeParse(data.projects);
+
```
[the remark this answers is not in the document]
Comment (barel-mishal) [reply actions/fetchProjectsData.ts:36]: Hi @Tamir198,

Yes, safeParse is coming from Zod. It’s useful for safely parsing and validating the data structure, ensuring that the data conforms to the expected schema. I suggest keeping it to maintain robust data validation.

File: app/[locale]/projects/page.tsx (hunk 1 above)
Comment (barel-mishal) [reply app/[locale]/projects/page.tsx:90]: Hi @Tamir198,

Good point. In this case, since we are not passing any locale-specific parameters to toLocaleLowerCase(), it behaves the same as toLowerCase(). I’ll update the code to use toLowerCase() for simplicity.

**Comment by barel-mishal** [comment]
All requested changes have been completed. Please let me know if any further modifications are needed.

File: components/Projects/ProjectCard/ProjectCard.tsx [hunk 7]
```diff
@@ -53,7 +47,7 @@ export default function ProjectCard({
         <ImageWithFallback
           width="108"
           height="108"
-          src={openGraphImageUrl}
+          src={url ?? ProjectImagePlaceholder}
```
Comment (Darkmift) [inline components/Projects/ProjectCard/ProjectCard.tsx:50]: nice

**Review by Avi-E-Koenig — APPROVED** [review]

**Comment by Darkmift** [comment]
Good approach seems api response was flattened and simplified.

File: components/Projects/ProjectCard/ProjectCard.tsx (hunk 7 above)
Comment (barel-mishal) [reply components/Projects/ProjectCard/ProjectCard.tsx:50]: Thanks

**Comment by barel-mishal** [comment]
i am a waiting for the approval

**Review by Tamir198 — APPROVED** [review]
Good work on the changes

**Comment by barel-mishal** [comment]
Ok please let me know what this change is going to merge. I want to add in another branch the fix for images

**Comment by Tamir198** [comment]
> Ok please let me know what this change is going to merge. I want to add in another branch the fix for images

If I was not clear, I liked you changes - good job no need to change anything else

File: actions/fetchProjectsData.ts [hunk 8]
```diff
@@ -39,9 +40,11 @@ async function fetchProjectsData({
 
   const parsedProjects = SummaryProjectType.array().safeParse(projects);
 
+  
   if (!parsedProjects.success) {
     throw new Error(`Failed to parse projects: ${parsedProjects.error}`);
   }
+  console.log(parsedProjects.data[0]);
```
Comment (Tamir198) [inline actions/fetchProjectsData.ts:48]: Hey, any reason to keep console log here?

File: components/Projects/ProjectCard/ProjectCard.tsx [hunk 9]
```diff
@@ -38,6 +38,8 @@ export default function ProjectCard({
 
   const t = useTranslations('Projects');
 
+  console.log(owner, name)
+
```
Comment (Tamir198) [inline components/Projects/ProjectCard/ProjectCard.tsx:42]: Same question in here

**Comment by Tamir198** [comment]
@barel-mishal  

Sorry I didn't noticed that this PR was already merged, if its got merged you can ignore my suggestions.
